[versions]
agp = "8.2.0-alpha15"
hilt-android = "2.47"
hilt-compiler = "1.0.0"
kotlin = "1.9.0"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.06.01"
navigation-compose = "2.6.0"
room-version = "2.5.2"
appcompat = "1.6.1"
runtime = "1.5.1"
ui-tooling = "1.5.1"

[libraries]
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-compiler" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compiler" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui-tooling" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version = "2.47" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }

ui = { group = "androidx.compose.ui", name = "ui", version = "1.6.0-alpha02" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version = "1.6.0-alpha02" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version = "1.6.0-alpha02" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version = "1.6.0-alpha02" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.6.0-alpha02" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version = "1.6.0-alpha02" }

material3 = { group = "androidx.compose.material3", name = "material3", version = "1.2.0-alpha04" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room-version" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-version" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room-version" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]

